# TSOP / SOT-457T SMD packages
base:
    series: SOT-457T
    family: TSOP
    description: 'TSOP SMD package'
    keywords: 'TSOP'
    fab_x_mm: 1.7
    #fab_y_mm: 3.1
    pin_distance_x_mm: 2.4
    pin_distance_y_mm: 0.95
    pin_width_x_mm: 0.7
    pin_width_y_mm: 0.55
    distance_from_last_pin_to_fab_y_mm: 0.5
variants:
    - pins: 6
      description_prefix: 'SOT-457T'
      additional_keywords: 'SOT-457T'
      datasheet: 'https://www.nxp.com/docs/en/package-information/SOT457.pdf'
